---
title: "Bike Sharing Demand"
author: "HO JIN"
editor: visual
---

## train/test file

```{r}
df <- read.csv("./bike_train.csv", header = T)
df1 <- read.csv("./bike_test.csv", header = T)
str(df)
str(df1)
```

## train, test 데이터 합치기

```{r}
library(dplyr)
alldf <- bind_rows(df, df1)
str(alldf)
summary(alldf)
```

## na 값 확인

```{r}
for (i in 1:length(alldf)){
    cat(colnames(alldf)[i],sum(is.na(alldf[,i])),'\n')
}
```

## na 값 0으로 변경 및 변경 확인

```{r}
alldf[is.na(alldf)] <- 0

for (i in 1:length(alldf)){
    cat(colnames(alldf)[i],sum(is.na(alldf[,i])),'\n')
}
```

## 일원분산분석

##### 계절이나 날씨 (독립변수, 범주형 변수)가 count 자전거 대여량 분산 분석을 사용하기 위해서는 정규성과 등분산성이 가정이 되야함. 그러나 자전거 데이터는 표본 크기가 커서 정규성 가정에 크게 제한을 받지 않는다.

```{r}
library(car)
bartlett.test(count ~ season, data = alldf)
bartlett.test(count ~ weather, data = alldf)
bartlett.test(count ~ holiday, data = alldf)
bartlett.test(count ~ workingday , data = alldf)
```

##### 집단 간 분산이 같다는 귀무가설을 기각하고 등분산성이 아니기에 oneway.test 함수를 사용함.

```{r}
oneway.test(count ~ season, data = alldf)
oneway.test(count ~ weather, data = alldf)
oneway.test(count ~ workingday, data = alldf)
```

```{r}
se <- aov(count ~ season, data = alldf,)
summary(se)
we <- aov(count ~ weather, data = alldf,)
summary(we)
wo <- aov(count ~ weather, data = alldf,)
summary(we)
ho <- aov(count ~ holiday, data = alldf,)
summary(ho)
```

```{r fig.height=10, fig.width=10}
library(gplots)
par(mfrow=c(3,1))
plotmeans(count~season ,data = alldf,
          barcol='tomato', barwidth=3, col='cornflowerblue', lwd=2,
          main='count & season')
plotmeans(count~weather ,data = alldf,
          barcol='tomato', barwidth=3, col='cornflowerblue', lwd=2,
          main='count & weather')
plotmeans(count~holiday ,data = alldf,
          barcol='tomato', barwidth=3, col='cornflowerblue', lwd=2,
          main='count & holiday')
par(mfrow = c(1,1))
```

```{r fig.height=10, fig.width=10}
par(mfrow=c(3,1))
boxplot(count~season ,data = alldf, col = 'tomato',
        main ='count & season')
boxplot(count~weather ,data = alldf, col = 'tomato',
        main ='count & weather')
boxplot(count~holiday ,data = alldf, col = 'tomato',
        main ='count & holiday')
par(mfrow = c(1,1))
```

### 다중회귀분석

```{r}
alldf <- alldf[, -1]
summary(alldf)
```

##### count와 나머지 변수

```{r}
model1 <- lm(count ~ . , data = alldf)
summary(model1)
```

##### count 와 temp

```{r}
model2 <- lm(count ~ temp + atemp, data = alldf)
summary(model2)
```

##### count 와 humidity

```{r}
model3 <- lm(count ~ humidity + windspeed, data = alldf)
summary(model3)
```

##### count 와 humidity, temp

```{r}
model4 <- lm(count ~ humidity + temp, data = alldf)
summary(model4)
```

##### count 와 atemp, windspeed

```{r}
model5 <- lm(count ~ atemp + windspeed, data = alldf)
summary(model5)
```

``` {#{r}
#model6 <- lm(count ~ humidity + weather, data = alldf)
#summary(model6)

#model7 <- lm(count ~ weather, data = alldf)
#summary(model7)
```

### 후진선택법

```{r}
mod.selected <- step(model1, direction = "backward")
summary(mod.selected)
```

### 상관분석

```{r}
library(psych)
pairs.panels(alldf)
```
